#Base image is node:argon
FROM node:argon

#Copy staging directory to the image
RUN mkdir /app
COPY docker_stage/webview /app

#Set working directory to /app
WORKDIR /app

#Install nodejs modules to /app on docker image
RUN npm install --loglevel=warn

#Set command to run on docker run
RUN chmod +x /app/app.js
CMD [ "nodejs", "/app/app.js" ]
